apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: {{ .Values.appName }}
        image: {{ .Values.image.backend.repository }}:{{ .Values.image.backend.tag }}
        ports:
        - containerPort: 5000
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: textmotion-config
              key: NODE_ENV
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: textmotion-secrets
              key: GEMINI_API_KEY
        - name: LAMBDA_FUNCTION_URL
          valueFrom:
            configMapKeyRef:
              name: textmotion-config
              key: LAMBDA_FUNCTION_URL
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-backend
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 5000
    targetPort: 5000
  selector:
    app: {{ .Values.appName }}