apiVersion: v1
kind: Secret
metadata:
  name: textmotion-secrets
type: Opaque
data:
  VITE_CLERK_PUBLISHABLE_KEY: "cGtfdGVzdF9kVzVwWm1sbFpDMXRZWE4wYVdabUxUazJMbU5zWlhKckxtRmpZMjkxYm5SekxtUmxkaVEK"
  GEMINI_API_KEY: "QUl6YVN5QjNOT1IyVWo4R3VQSW1LU0txVVFINWp1RXdSSlZTYmwwCg=="

